export const dummyData = [
  {
    fullName: "John Doe",
    dob: "1995-05-15",
    gender: "Male",
    contactNumber: "9876543210",
    email: "john.doe@example.com",
    currentAddress: "1234 Elm Street, Springfield",
    permanentAddress: "5678 Oak Avenue, Shelbyville",
    motherName: "Jane Doe",
    fatherName: "Richard Doe",
    alternateNumber: "8765432109",
    aadharCard: "1234-5678-9012",
    panCard: "ABCDE1234F",
    reference: "Alice Johnson",
    highestDegree: "B.Tech",
    universityCollegeName: "Springfield University",
    yearOfPassing: "2018",
    specializationMajor: "Computer Science",
    percentageCgpa: "8.5",
    longMemo: "Passionate developer with 2 years of experience.",
    selectedCourse: "Full Stack Web Development",
    paymentType: "Credit Card",
  },
  {
    fullName: "Emily Smith",
    dob: "1998-08-20",
    gender: "Female",
    contactNumber: "9123456780",
    email: "emily.smith@example.com",
    currentAddress: "789 Pine Road, Riverside",
    permanentAddress: "123 Willow Lane, Hillside",
    motherName: "Martha Smith",
    fatherName: "George Smith",
    alternateNumber: "9023456781",
    aadharCard: "4321-8765-0987",
    panCard: "FGHIJ5678K",
    reference: "Bob Brown",
    highestDegree: "MBA",
    universityCollegeName: "Riverside Business School",
    yearOfPassing: "2021",
    specializationMajor: "Marketing",
    percentageCgpa: "7.9",
    longMemo: "Strong communication and leadership skills.",
    selectedCourse: "Digital Marketing",
    paymentType: "UPI",
  },
  {
    fullName: "David Lee",
    dob: "1992-03-10",
    gender: "Male",
    contactNumber: "9012345678",
    email: "david.lee@example.com",
    currentAddress: "456 Maple Street, Greenfield",
    permanentAddress: "789 Birch Road, Woodtown",
    motherName: "Linda Lee",
    fatherName: "Samuel Lee",
    alternateNumber: "8901234567",
    aadharCard: "5678-1234-8765",
    panCard: "KLMNO2345P",
    reference: "Cathy Wilson",
    highestDegree: "M.Sc",
    universityCollegeName: "Greenfield University",
    yearOfPassing: "2016",
    specializationMajor: "Physics",
    percentageCgpa: "9.1",
    longMemo: "Enthusiastic researcher with a passion for innovation.",
    selectedCourse: "Data Science",
    paymentType: "Debit Card",
  },
  {
    fullName: "Sophia Clark",
    dob: "1997-12-05",
    gender: "Female",
    contactNumber: "9345678901",
    email: "sophia.clark@example.com",
    currentAddress: "10 Lotus Street, Blossom City",
    permanentAddress: "22 Rose Lane, Garden Town",
    motherName: "Nancy Clark",
    fatherName: "William Clark",
    alternateNumber: "9001234568",
    aadharCard: "8765-4321-5678",
    panCard: "WXYZP7890Q",
    reference: "Oliver Mills",
    highestDegree: "BBA",
    universityCollegeName: "Blossom Business School",
    yearOfPassing: "2019",
    specializationMajor: "Finance",
    percentageCgpa: "8.0",
    longMemo: "Financial analyst with expertise in market research.",
    selectedCourse: "Financial Modeling",
    paymentType: "Net Banking",
  },
  {
    fullName: "Liam Brown",
    dob: "1994-06-21",
    gender: "Male",
    contactNumber: "9234567890",
    email: "liam.brown@example.com",
    currentAddress: "100 River Avenue, Bridgeport",
    permanentAddress: "15 Oakwood Road, Lakeside",
    motherName: "Helen Brown",
    fatherName: "Charles Brown",
    alternateNumber: "9009876543",
    aadharCard: "5678-4321-8765",
    panCard: "OPQRS1234T",
    reference: "Nathan Moore",
    highestDegree: "B.Com",
    universityCollegeName: "Bridgeport Commerce College",
    yearOfPassing: "2017",
    specializationMajor: "Accounting",
    percentageCgpa: "7.5",
    longMemo: "Experienced accountant with a knack for numbers.",
    selectedCourse: "Corporate Accounting",
    paymentType: "Cash",
  },
  {
    fullName: "Ava Wilson",
    dob: "1999-09-30",
    gender: "Female",
    contactNumber: "9123896543",
    email: "ava.wilson@example.com",
    currentAddress: "789 Cedar Drive, Harmony",
    permanentAddress: "23 Beech Lane, Willowtown",
    motherName: "Grace Wilson",
    fatherName: "John Wilson",
    alternateNumber: "9304567891",
    aadharCard: "6789-2345-1234",
    panCard: "TUVWX6789Y",
    reference: "Jessica Hall",
    highestDegree: "B.Sc",
    universityCollegeName: "Harmony Science College",
    yearOfPassing: "2022",
    specializationMajor: "Biotechnology",
    percentageCgpa: "8.8",
    longMemo: "Biotech enthusiast with a passion for lab research.",
    selectedCourse: "Bioinformatics",
    paymentType: "Wallet",
  },
  {
    fullName: "Mason Miller",
    dob: "1990-02-14",
    gender: "Male",
    contactNumber: "8901234567",
    email: "mason.miller@example.com",
    currentAddress: "44 West Street, Uptown",
    permanentAddress: "33 North Road, Downtown",
    motherName: "Diane Miller",
    fatherName: "James Miller",
    alternateNumber: "9112345678",
    aadharCard: "4321-8765-3456",
    panCard: "LMNOP5678Q",
    reference: "Gary Cole",
    highestDegree: "B.A.",
    universityCollegeName: "Uptown Arts College",
    yearOfPassing: "2012",
    specializationMajor: "Literature",
    percentageCgpa: "7.0",
    longMemo: "Creative writer with a flair for storytelling.",
    selectedCourse: "Creative Writing",
    paymentType: "Cheque",
  },
];
